### ISSUE TITLE
Ability to Change JSON Schema Graph Node Vertical Spacing / Increase Max Height

### ISSUE THREAD

**Issue by grant** [jsonsystems/json-schema#102]
Hey, cool tool!

I like the graph feature, but I don't know how to increase the vertical spacing between nodes. Without this, it's hard to visualize large schemas. I think there's a limit on the max height of the viz.

Even if there's some JS variable I can tweak, that'd be cool.

![Screen Shot 2020-10-13 at 01 37 06](https://user-images.githubusercontent.com/744973/95824502-04ae8880-0cf5-11eb-9e62-bb9c781ffc62.png)

---

Example data:

https://raw.githubusercontent.com/googleapis/google-cloudevents/master/jsonschema/google/events/cloud/audit/v1/LogEntryData.json

**Comment by jsonsystems** [comment]
@grant Thank you for providing the sample data. I played around with this and can see the problem comes from the height of the canvas which squashes the nodes to fit. I'll look into this more and update this issue. Thank you for taking the time to post this issue!

![image](https://user-images.githubusercontent.com/1623996/99184609-13e18580-273c-11eb-8159-24dada8c3152.png)

**Comment by jackwootton** [comment]
@grant Thanks for taking the time to post this issue. As you will have seen the graph has been removed in the new version of www.jsonschema.net. I would like to re-implement it but with more thought from users. Do you mind opening a new FR at https://github.com/jsonsystems/public if this is still relevant to you?
