### ISSUE TITLE
link to web app source code?

### ISSUE THREAD

**Issue by guidorice** [jsonsystems/json-schema#30]
Hi, jsonschema.net is a great resource. Is the source for the web app available? Sorry if this is an obvious thing- I looked in the github repo and in your gh organization. thanks in advance.

**Comment by erd0s** [comment]
That would be great, I came here to see if I could contribute some code but I can only submit issues, it makes me feel so whiny, @jackwootton do you have plans to make it available? Or do you prefer to keep it closed for some monetisation purposes later (both are totally acceptable)

**Comment by Gdewilde** [comment]
@jackwootton any updates on this? We're looking to build this internally if it stays closed source.

**Comment by luzlab** [comment]
@jackwootton  Any update on this?

**Comment by ndunks** [comment]
It will be great if we can make a pull request

**Comment by GeniusGeng** [comment]
Same here, I want to implement such function in my work,  any update?

**Comment by jsonsystems** [comment]
Thanks for everyone's interest. Sorry for the slow response, because GitHub orders issues by date opened and not update, this slipped down my list. Yes, you can reorder them, but the order is not saved :-/

What kind of package are people looking for? Npm? Pip? Source code (Python3)? At the moment the code base is changing daily, because of this I don't want the overhead of managing pull requests on top of my own development. The good news is I am dramatically cutting down the number of lines of code and greatly simplifying the implementation.  

I also don't have any plans to monetise this - I don't think that's even possible. However I do want development to be controlled right now while I decide on some architectural decisions. For example how much logic to put on the server Vs the client. I also want to spend my time implementing user login and give the users a place to save their work.

**Comment by jsonsystems** [comment]
I'm merging other similar issues into this one.

**Comment by guidorice** [comment]
Thanks @jsonsystems, good to hear! I was trying to remember the specific thing I was looking for regarding the front-end code. I think it probably was that I had some kind of glitch with the web app and wanted to file an issue, or attempt to fix it.

**Comment by thomas4019** [comment]
@jsonsystems I'm also interested in this so I can integrate with my open-source [JSON REST API server](https://github.com/thomas4019/expressa). I'm also up to help in any way with cleaning up, adding tests or publishing to npm. Thanks!

**Comment by andrewsitt** [comment]
@jsonsystems, I'm also interestin in this. Could you give us an update when you might be releasing the code for this? Or if you're not planning to do so now?

**Comment by Gdewilde** [comment]
Having an NPM package would be great. Existing packages like https://www.npmjs.com/package/json-schema-generator like much of the functionality you offer. 

Maybe you can set up an Open Collective to sponsor the development? Thanks for considering.

**Comment by luzlab** [comment]
I've written a basic express app that publishes our schema library as either JSON Schema or AVRO formats.  But we don't have any UI to let users explore and play with a catalog of schemas. 

Didn't the web app have a  way to browser through various published schemas and test them out? I just logged into the web app and couldn't find this feature anymore. Was it removed recently?
