### ISSUE TITLE
decimal/float amounts entered in JSON window convert to integer

### ISSUE THREAD

**Issue by yesthesoup** [jsonsystems/json-schema#66]
JSON example:
```
{
  "id": "12345",
  "totals": {
    "sub_total": 100.00,
    "discounts": 0.00,
    "taxes": 0.00,
    "total": 100.00
  }
}
```
I copy this into the left window, and click Load Schema, which it then converts to
```
{
    "id": "12345",
    "totals": {
        "sub_total": 100,
        "discounts": 0,
        "taxes": 0,
        "total": 100
    }
}
```
And results in a schema with types of "integer" instead of "number".

**Comment by jackwootton** [comment]
Because `12.0 === 12` is `true`, there's no way to make the current implementation (`JSON.parse`  followed with `JSON.stringify`) to work. This requires more thought.

I'm going to disable the formatting of input until I can make this work properly. Formatting is a nice-to-have, but the bug you experienced could be really problematic.

I'm deploying this now.

Remember, you can force `number` for (all) numeric values in the settings, but then this will force it for integers too:

![image](https://user-images.githubusercontent.com/1623996/75709648-fad29a80-5cba-11ea-8b86-3294067b6e67.png)
