### ISSUE TITLE
https://jsonschema.net/ is throwing 502 error.

### ISSUE THREAD

**Issue by Ganeshacgan** [jsonsystems/json-schema#90]
https://jsonschema.net/ is throwing 502 error, when i put some json data convert into schema.
<img width="1440" alt="Screenshot 2020-07-06 at 7 28 40 PM" src="https://user-images.githubusercontent.com/67911973/86603199-54c4d300-bfc1-11ea-8093-854d2ab4c68d.png">

**Comment by jsonsystems** [comment]
I'm looking at this now. Thank you for reporting it.

**Comment by jsonsystems** [comment]
This sholuld now be fixed. The Kubernetes cluster hosting the API was down. I'll need to look into this properly to find out why I didn't receive an alert about an unhealthy backend.

It looks like the underlying cause was the underlying machine running out of memory. Since I pay for a machine I don't use anything special, only 1 vCPU, 3.75 GB memory. It looks like I'll need to upgrade this.

**Comment by Ganeshacgan** [comment]
Hello,

I am facing the issue again, this time new error -take a look at the screenshot.
<img width="1440" alt="Screenshot 2020-07-07 at 4 56 41 PM" src="https://user-images.githubusercontent.com/67911973/86773313-256e9e80-c073-11ea-9035-3f08dfb27207.png">

**Comment by jsonsystems** [comment]
@Ganeshacgan This is working for me. What browser are you using and are you behind any proxies or firewalls that could be modifying any network calls?

**Comment by Ganeshacgan** [comment]
@jsonsystems Now it is working fine, in the noon time around 2PM IST, it was not.
